name: OrbisEconomy
version: 2.0.0
main: me.Short.OrbisEconomy.OrbisEconomy
description: A simple, yet customisable and robust, Vault-based economy provider.
api-version: '1.21.11'

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    LiteBans:
      load: BEFORE
      required: false
      join-classpath: true
    EconomyBridge:
      load: BEFORE
      required: false
      join-classpath: true
    OrbisLoot:
      load: AFTER
      required: false
      join-classpath: false

permissions:

  orbiseconomy.*:
    description: "All OrbisEconomy permissions."
    default: op

  orbiseconomy.balancetop.exclude:
    description: "Players with this permission will be excluded from the /balancetop list, if enabled in config.yml."
    default: op

  orbiseconomy.command.*:
    description: "Access to all OrbisEconomy commands and sub-commands."
    default: op
    children:
      orbiseconomy.command.economy.*: true
      orbiseconomy.command.balance: true
      orbiseconomy.command.balance.others: true
      orbiseconomy.command.pay: true
      orbiseconomy.command.orbs.*: true

  orbiseconomy.command.economy.*:
    description: "Access to /economy and all of its sub-commands."
    default: op
    children:
      orbiseconomy.command.economy: true
      orbiseconomy.command.economy.set: true
      orbiseconomy.command.economy.give: true
      orbiseconomy.command.economy.take: true
      orbiseconomy.command.economy.reset: true
      orbiseconomy.command.economy.reload: true

  orbiseconomy.command.economy:
    description: "Access to /economy."
    default: op

  orbiseconomy.command.economy.set:
    description: "Access to /economy set [currency] <player> <amount>."
    default: op

  orbiseconomy.command.economy.give:
    description: "Access to /economy give [currency] <player> <amount>."
    default: op

  orbiseconomy.command.economy.take:
    description: "Access to /economy take [currency] <player> <amount>."
    default: op

  orbiseconomy.command.economy.reset:
    description: "Access to /economy reset [currency] <player>."
    default: op

  orbiseconomy.command.economy.reload:
    description: "Access to /economy reload."
    default: op

  orbiseconomy.command.balance:
    description: "Access to /balance."
    default: true

  orbiseconomy.command.balance.others:
    description: "Access to /balance [player]."
    default: true

  orbiseconomy.command.balancetop:
    description: "Access to /balancetop."
    default: true

  orbiseconomy.command.pay:
    description: "Access to /pay."
    default: true

  orbiseconomy.command.paytoggle:
    description: "Access to /paytoggle."
    default: true

  orbiseconomy.command.orbs.*:
    description: "Access to /orbs and all of its sub-commands."
    default: op
    children:
      orbiseconomy.command.orbs: true
      orbiseconomy.command.orbs.balance: true
      orbiseconomy.command.orbs.balance.others: true
      orbiseconomy.command.orbs.give: true
      orbiseconomy.command.orbs.take: true
      orbiseconomy.command.orbs.set: true

  orbiseconomy.command.orbs:
    description: "Access to /orbs."
    default: true

  orbiseconomy.command.orbs.balance:
    description: "Access to /orbs balance."
    default: true

  orbiseconomy.command.orbs.balance.others:
    description: "Access to /orbs balance [player] (orbs currency wrapper)."
    default: true

  orbiseconomy.command.orbs.give:
    description: "Access to /orbs give <player> <amount> (orbs currency wrapper)."
    default: op

  orbiseconomy.command.orbs.take:
    description: "Access to /orbs take <player> <amount> (orbs currency wrapper)."
    default: op

  orbiseconomy.command.orbs.set:
    description: "Access to /orbs set <player> <amount> (orbs currency wrapper)."
    default: op